name: Buy win
on:
  schedule:
    - cron: 0 10 * * 1 # every Monday on 07:00 PM (KST)
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Buy win
    steps:  

      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      - name: Run Scripts
        run: make buy-win
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COUNT: ${{ secrets.COUNT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL:  ${{ secrets.DISCORD_WEBHOOK_URL }}